### ISSUE TITLE
ANL + Tensorflow image scaler

### ISSUE THREAD

**Issue by fire** [Xrayez/godot-anl#15]
I had an idea to make a tensorflow image scaler, do you think it'll fit with the visual node paradigm or should I do it another way?

**Comment by Xrayez** [comment]
Not sure what are you talking about, what's the use case? ANL can generate images of (any) size so there's no need to resize them. Or are you talking about graph-based way to resize images? I've never worked with Tensorflow so I'm useless here.

**Comment by fire** [comment]
The second one. A graph-based way to resize images. Basically a graph-based way to work on images? textures? 

Something like https://rodzilla.itch.io/material-maker.

**Comment by Xrayez** [comment]
ANL can resize noise via `Scale` node, but it can't actually accept an `Image` or `Texture` as some sort of uniform as input to work with... But you *can* make up images as output currently, as well as generate normal and bump map from it. I think it would be cool to perform noise operations on an input image.

I think the described approach would fit just nice as a paradigm.

**Comment by Xrayez** [comment]
Not sure if this can be applied/relevant to ANL so closing for now.
