### ISSUE TITLE
Elementary noise generators are missing

### ISSUE THREAD

**Issue by Xrayez** [Xrayez/godot-anl#2]
Value, gradient, gradval, white and simplex noise generators are not exposed to the module:
```cpp
...
double value_noise2D(double x, double y, unsigned int seed, interp_func interp);
double gradient_noise2D(double x, double y, unsigned int seed, interp_func interp);
double gradval_noise2D(double x, double y, unsigned int seed, interp_func interp);
double white_noise2D(double x, double y, unsigned int seed, interp_func interp);
double simplex_noise2D(double x, double y, unsigned int seed, interp_func interp);
...
```

I'm not sure whether they're needed since the noise can be obtained from constructed kernel. But I think  having those wouldn't hurt.

**Comment by Fefe-Hern** [comment]
From my first view of the module, and library it connects to:
It appears that the intended functionality would be to be able to write code such as
```gdscript
var n = AnlNoise.new()
n.white_noise2D(x, y, seed, AnlNoise.INTERP_QUINTIC)
```
Would that be its intended use?

Aside from that, I do believe that if any changes to the main noise library have to be made; we should either discuss a pull-request with JTippetts or fork and provide the proper edits to customize the lib.

**Comment by Xrayez** [comment]
> Would that be its intended use?

Yeah, with the naming convention of snake_case:
```gdscript
n.white_noise_2d(x, y, seed, AnlNoise.INTERP_QUINTIC)
```
I think that the `interp_func`s could be initialized in the `AnlNoise` class, not sure.

>Aside from that, I do believe that if any changes to the main noise library have to be made; we should either discuss a pull-request with JTippetts or fork and provide the proper edits to customize the lib.

I personally don't see the reason in adding new features to the original library by ourselves. These feature requests should be directed to JTippetts directly IMO. I've already made some changes to the library. What I've essentially did is converted header-only library back to ordinary h/cpp structure in order for it to compile properly with Scons build system. Whenever I see new commits, I "merge" those as well.

**Comment by Xrayez** [comment]
I think there's no real need for this, there are enough methods already, this would only add more confusion, especially with visual noise being implemented, so closing.
